# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.runs/synth_1/air_soc.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.cache/wt [current_project]
set_property parent.project_path D:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog D:/gitcls/air-soc-qspi/rtl/header.vh
read_verilog -library xil_defaultlib -sv {
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/vendor/pulp_platform_common_cells/src/cf_math_pkg.sv
  D:/gitcls/air-soc-qspi/rtl/src/memory/cache.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_aligner.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/include/cv32e40p_pkg.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_alu.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_alu_div.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/include/cv32e40p_apu_core_pkg.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_apu_disp.sv
  D:/gitcls/air-soc-qspi/rtl/src/util/cv32e40p_clock_gate.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_compressed_decoder.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_controller.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_core.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_cs_registers.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/include/cv32e40p_fpu_pkg.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_decoder.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_ex_stage.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_ff_one.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_fifo.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_pkg.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_fp_wrapper.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_hwloop_regs.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_id_stage.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_if_stage.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_int_controller.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_load_store_unit.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_mult.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_obi_interface.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_popcnt.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_prefetch_buffer.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_prefetch_controller.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_register_file_latch.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_sleep_unit.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/cv32e40p_top.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_block.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_fmt_slice.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_top.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/vendor/pulp_platform_common_cells/src/lzc.sv
  D:/gitcls/air-soc-qspi/rtl/src/databus/obi_demux.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/qspi/qspi_controller.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/qspi/qspi_controller_obi.sv
  D:/gitcls/air-soc-qspi/rtl/src/memory/ram.sv
  D:/gitcls/air-soc-qspi/cv32e40p/rtl/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv
  D:/gitcls/air-soc-qspi/rtl/src/memory/simpleuart.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/timer/timer.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/timer/timer_controller.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/timer/timer_controller_obi.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/uart/uart_controller.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/uart/uart_controller_obi.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/uart/uart_rx.sv
  D:/gitcls/air-soc-qspi/rtl/src/peripherals/uart/uart_tx.sv
  D:/gitcls/air-soc-qspi/rtl/src/soc/air_soc.sv
}
read_ip -quiet D:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/gitcls/air-soc-qspi/xdc/basys3.xdc
set_property used_in_implementation false [get_files D:/gitcls/air-soc-qspi/xdc/basys3.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/gitcls/air-soc-qspi/vivado/airsoc-qspi-zc706/airsoc-qspi-zc706.srcs/utils_1/imports/synth_1/air_soc.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top air_soc -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef air_soc.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file air_soc_utilization_synth.rpt -pb air_soc_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
